//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id_comment { get; set; }
        public int Id_movie { get; set; }
        public int Id_user { get; set; }
        public string Comment1 { get; set; }
        public int Rating { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
    }
}
