//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieLibraryEntities : DbContext
    {
        public MovieLibraryEntities()
            : base("name=MovieLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<MovieType> MovieType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
